M48
; DRILL file {KiCad 7.0.7} date Mon May 20 18:32:23 2024
; FORMAT={-:-/ absolute / inch / decimal}
; #@! TF.CreationDate,2024-05-20T18:32:23-04:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,7.0.7
; #@! TF.FileFunction,NonPlated,1,2,NPTH
FMAT,2
INCH
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C0.0866
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T2C0.1378
%
G90
G05
T1
X3.937Y-3.4843
X3.9764Y-5.1969
X5.1575Y-6.1417
X5.1772Y-2.9488
T2
X4.711Y-3.7976
T0
M30
