M48
; DRILL file {KiCad 8.0.8} date 2025-03-09T10:31:59-0700
; FORMAT={-:-/ absolute / inch / decimal}
; #@! TF.CreationDate,2025-03-09T10:31:59-07:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,8.0.8
; #@! TF.FileFunction,NonPlated,1,4,NPTH
FMAT,2
INCH
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C0.0256
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T2C0.1260
%
G90
G05
T1
X7.2244Y-3.2705
X7.2244Y-3.498
T2
X4.2638Y-2.8154
X4.2638Y-4.7445
X6.5472Y-2.8154
X6.5472Y-4.7445
M30
