[env]
lib_deps = 
lib_compat_mode = strict
build_flags = 
	-Wno-unknown-pragmas
	-std=gnu++17

[env:stm32h723vehx]
platform = ststm32
framework = arduino
board = stm32h723vehx
board_build.variants_dir = custom_variants
board_build.ldscript = ldscripts/ldscript.ld
lib_deps =
	${env.lib_deps}
	Wire
	stm32duino/STM32duino STM32SD
	https://github.com/stm32duino/FatFs.git
	jgromes/RadioLib@^6.6.0
build_flags =
	${env.build_flags}
	-D ENV_STM
	-D STM32
	-D ARDUINO_GENERIC_H723VEHX
	-D USE_PWR_LDO_SUPPLY
    -D PIO_FRAMEWORK_ARDUINO_ENABLE_CDC
    -D USBCON
    -D USE_USB_HS
    -D USE_USB_HS_IN_FS
	-D RADIOLIB_DEBUG_BASIC       ; (1)   // basic debugging (e.g. reporting GPIO timeouts or module not being found)
	-D RADIOLIB_DEBUG_PROTOCOL    ; (1)   // protocol information (e.g. LoRaWAN internal information)
	-D RADIOLIB_DEBUG_SPI         ; (1)   // verbose transcription of all SPI communication - produces large debug logs!