M48
; DRILL file {KiCad 9.0.0} date 2025-05-09T11:31:14-0400
; FORMAT={-:-/ absolute / inch / decimal}
; #@! TF.CreationDate,2025-05-09T11:31:14-04:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,9.0.0
; #@! TF.FileFunction,Plated,1,2,PTH
FMAT,2
INCH
; #@! TA.AperFunction,Plated,PTH,ComponentDrill
T1C0.0866
; #@! TA.AperFunction,Plated,PTH,ComponentDrill
T2C0.1260
%
G90
G05
T1
X3.6417Y-4.685
X3.8386Y-4.685
T2
X3.7402Y-3.7402
X3.7402Y-4.3701
M30
