[platformio]
default_envs = teensy41

[env:teensy41]
platform = teensy
board = teensy41
framework = arduino
build_flags =
    -std=gnu++17
    -Wno-unknown-pragmas
lib_compat_mode = strict
lib_deps =
    Wire
