; PlatformIO Project Configuration File
;
;   Build options: build flags, source filter
;   Upload options: custom upload port, speed and extra flags
;   Library options: dependencies, extra library storages
;   Advanced options: extra scripting
;
; Please visit documentation for the other options and examples
; https://docs.platformio.org/page/projectconf.html
[platformio]
default_envs = teensy41

[env:teensy41]
platform = teensy
board = teensy41
framework = arduino
lib_extra_dirs = /lib/imumaths
build_src_filter = +<*> -<StateTest/*> +<StateTest/TestUtils.h> -<GroundStationReceiver/*>
build_flags = 
	-Wno-unknown-pragmas -g
lib_compat_mode = strict
check_src_filters = -<*> +<src/*> +<include/*> +<lib/*>
check_flags =
	cppcheck: --suppressions-list=cppcheck-suppressions.txt -j 12
lib_ldf_mode = deep+