[project]
name = "kalman-filter-sim"
version = "0.1.0"
description = "Python simulation environment for Kalman filter development and testing"

[build-system]
build-backend = "flit_core.buildapi"
requires = ["flit_core >=3.2,<4"]