; PlatformIO Project Configuration File
;
;   Build options: build flags, source filter
;   Upload options: custom upload port, speed and extra flags
;   Library options: dependencies, extra library storages
;   Advanced options: extra scripting
;
; Please visit documentation for the other options and examples
; https://docs.platformio.org/page/projectconf.html

[env:ESP32FC]
platform = espressif32
board = esp32-s3-devkitc-1
framework = arduino
lib_deps =
    https://github.com/jgromes/RadioLib.git#5b901a33338887e38960b6972358e19cc938f1b4
    symlink://C:/Users/Drew/Documents/arc-protocol
    h2zero/NimBLE-Arduino @ ^2.1.0
upload_speed = 115200
upload_flags = --no-stub
build_flags =
    ; -DRADIOLIB_DEBUG_BASIC=1
build_src_filter =
    +<*>
    -<radio_ping_rx.cpp>
    -<radio_ping_tx.cpp>
    -<radio_ping_type2gt_tx.cpp>

[env:ESP32FC-ping-rx]
extends = env:ESP32FC
build_src_filter =
    -<*>
    +<radio_ping_rx.cpp>

[env:ESP32FC-ping-tx]
extends = env:ESP32FC
build_src_filter =
    -<*>
    +<radio_ping_tx.cpp>

[env:ESP32FC-ping-type2gt-tx]
extends = env:ESP32FC
build_src_filter =
    -<*>
    +<Type_2GT.cpp>
    +<Type_2GT.h>
    +<radio_ping_type2gt_tx.cpp>
