M48
; DRILL file {KiCad 7.0.7} date Mon May 20 18:34:09 2024
; FORMAT={-:-/ absolute / inch / decimal}
; #@! TF.CreationDate,2024-05-20T18:34:09-04:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,7.0.7
; #@! TF.FileFunction,NonPlated,1,2,NPTH
FMAT,2
INCH
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C0.0866
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T2C0.0941
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T3C0.1248
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T4C0.1358
%
G90
G05
T1
X4.063Y-2.0236
X4.0709Y-5.2677
X5.9646Y-2.0276
X5.9646Y-5.2756
T2
X5.7484Y-5.0677
T3
X5.0593Y-2.5709
X5.0593Y-4.7441
T4
X4.3701Y-4.7441
X5.7484Y-2.5709
T0
M30
