[env:stm32h723vehx]
platform = ststm32
framework = arduino
lib_deps =
    https://github.com/jgromes/RadioLib.git#5b901a33338887e38960b6972358e19cc938f1b4
    symlink://C:/Users/Drew/Documents/arc-protocol
board = stm32h723vehx
board_build.variants_dir = custom_variants
board_build.ldscript = ldscripts/ldscript.ld
board_build.arduino.USB = disabled
build_flags =
    -DSTM32
    -DARDUINO_GENERIC_H723VEHX
    -DSERIAL_RX_BUFFER_SIZE=2048
    -D SERIAL_UART_INSTANCE=1
    ; -DRADIOLIB_DEBUG_BASIC
    ; -DRADIOLIB_DEBUG_SPI
    -D RADIOLIB_VERBOSE_ASSERT=1
    -Wl,-u,_printf_float
    -DHAL_PCD_MODULE_DISABLED
build_unflags = -DUSBCON -DUSBD_USE_CDC
build_src_filter =
    +<*>
    -<radio_ping_tx.cpp>
    -<radio_ping_rx.cpp>

[env:teensy]
platform=teensy
framework = arduino
board = teensy41
lib_deps =
	${env.lib_deps}
build_flags =
	${env.build_flags}
	-DTEENSY

[env:stm32h723vehx-ping-tx]
extends = env:stm32h723vehx
build_src_filter =
    -<*>
    +<radio_ping_tx.cpp>

[env:stm32h723vehx-ping-rx]
extends = env:stm32h723vehx
build_src_filter =
    -<*>
    +<radio_ping_rx.cpp>

[env:stm32h723vehx-debug]
extends = env:stm32h723vehx
build_flags =
    ${env:stm32h723vehx.build_flags}
    -DRADIO_HOST_UART_DEBUG=1
