M48
; DRILL file {KiCad 8.0.8} date 2025-03-10T12:23:33-0400
; FORMAT={-:-/ absolute / metric / decimal}
; #@! TF.CreationDate,2025-03-10T12:23:33-04:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,8.0.8
; #@! TF.FileFunction,NonPlated,1,4,NPTH
FMAT,2
METRIC
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C0.650
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T2C3.200
%
G90
G05
T1
X151.23Y-130.02
X157.01Y-130.02
T2
X131.5Y-47.5
X131.5Y-132.5
X168.5Y-47.5
X168.5Y-132.5
M30
