M48
; DRILL file {KiCad 8.0.8} date 2025-03-09T10:35:20-0700
; FORMAT={-:-/ absolute / inch / decimal}
; #@! TF.CreationDate,2025-03-09T10:35:20-07:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,8.0.8
; #@! TF.FileFunction,NonPlated,1,4,NPTH
FMAT,2
INCH
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C0.0256
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T2C0.1260
%
G90
G05
T1
X5.7846Y-6.6465
X6.0122Y-6.6465
T2
X5.0Y-2.6772
X5.0Y-6.6929
X6.5354Y-2.6772
X6.5354Y-6.6929
M30
