// AUTOGENERATED FILE
// compileHeaders.py v1

#ifndef H_radio_config_Si4464
#define H_radio_config_Si4464

// Original file: radio_config_Si4464.h
// Register values generated using Silicon Labs WDS (Copyright 2017 Silicon Laboratories, Inc.)

// INPUT DATA
/*
// Crys_freq(Hz): 30000000    Crys_tol(ppm): 0.5    IF_mode: 2    High_perf_Ch_Fil: 1    OSRtune: 0    Ch_Fil_Bw_AFC: 1    ANT_DIV: 0    PM_pattern: 0    
// MOD_type: 5    Rsymb(sps): 50000    Fdev(Hz): 25000    RXBW(Hz): 150000    Manchester: 0    AFC_en: 1    Rsymb_error: 0.0    Chip-Version: 3    
// RF Freq.(MHz): 222.5    API_TC: 29    fhst: 250000    inputBW: 0    BERT: 0    RAW_dout: 0    D_source: 0    Hi_pfm_div: 1    
// 
// # RX IF frequency is  -468750 Hz
// # WB filter 2 (BW = 206.12 kHz);  NB-filter 2 (BW = 206.12 kHz)
// 
// Modulation index: 1
*/

// Property values
#define RF_MODEM_AGC_CONTROL_1 0x11, 0x20, 0x01, 0x35, 0xE2
#define RF_MODEM_CHFLT_RX1_CHFLT_COE13_7_0_12 0x11, 0x21, 0x0C, 0x00, 0xFF, 0xC4, 0x30, 0x7F, 0xF5, 0xB5, 0xB8, 0xDE, 0x05, 0x17, 0x16, 0x0C
#define RF_MODEM_CHFLT_RX1_CHFLT_COE1_7_0_12 0x11, 0x21, 0x0C, 0x0C, 0x03, 0x00, 0x15, 0xFF, 0x00, 0x00, 0xFF, 0xC4, 0x30, 0x7F, 0xF5, 0xB5
#define RF_MODEM_CHFLT_RX2_CHFLT_COE7_7_0_12 0x11, 0x21, 0x0C, 0x18, 0xB8, 0xDE, 0x05, 0x17, 0x16, 0x0C, 0x03, 0x00, 0x15, 0xFF, 0x00, 0x00
#define RF_SYNTH_PFDCP_CPFF_7 0x11, 0x23, 0x07, 0x00, 0x2C, 0x0E, 0x0B, 0x04, 0x0C, 0x73, 0x03
#define RF_PA_MODE_4 0x11, 0x22, 0x01, 0x3, 0x3D


// Configuration array
const unsigned char CONFIG_radio_config_Si4464[] = { \
	0x5, RF_MODEM_AGC_CONTROL_1, \
	0x10, RF_MODEM_CHFLT_RX1_CHFLT_COE13_7_0_12, \
	0x10, RF_MODEM_CHFLT_RX1_CHFLT_COE1_7_0_12, \
	0x10, RF_MODEM_CHFLT_RX2_CHFLT_COE7_7_0_12, \
	0xb, RF_SYNTH_PFDCP_CPFF_7, \
	0x5, RF_PA_MODE_4, \
};
#endif