M48
; DRILL file KiCad 10.0.0 date 2026-03-28T09:32:16
; FORMAT={-:-/ absolute / inch / decimal}
; #@! TF.CreationDate,2026-03-28T09:32:16-04:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,10.0.0
; #@! TF.FileFunction,NonPlated,1,4,NPTH
FMAT,2
INCH
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C0.0256
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T2C0.1260
%
G90
G05
T1
X10.3563Y-4.1392
X10.3563Y-4.3667
T2
X8.8923Y-3.128
X10.5207Y-3.1252
X10.5226Y-5.2805
M30
