M48
; DRILL file {KiCad 7.0.7} date Thu Oct 19 21:27:59 2023
; FORMAT={-:-/ absolute / inch / decimal}
; #@! TF.CreationDate,2023-10-19T21:27:59-04:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,7.0.7
; #@! TF.FileFunction,Plated,1,2,PTH
FMAT,2
INCH
; #@! TA.AperFunction,Plated,PTH,ViaDrill
T1C0.0157
; #@! TA.AperFunction,Plated,PTH,ComponentDrill
T2C0.0394
%
G90
G05
T1
X5.5Y-3.7
X5.5Y-3.9
X5.5Y-4.0
X5.6Y-3.5
X5.6Y-3.7
X5.6676Y-3.7
X5.7Y-4.0
X5.7398Y-3.9995
X5.8Y-4.1
X6.1Y-3.6
T2
X6.3Y-3.8
X6.3Y-3.9
X6.3Y-4.0
X6.3Y-4.1
T0
M30
